### ISSUE TITLE
Help me with the connections

### ISSUE THREAD

**Issue by PreethamRU** [CascoLogix/E07-M1101S_V2#1]
Hi, can you share connection diagram for cc1101 with MSP430 ?

**Comment by CascoLogix** [comment]
The connections of the MSP430 to the E07-M1101S_V2 are detailed in this header file: [Pinouts.h](https://github.com/CascoLogix/E07-M1101S_V2/blob/master/Pinouts.h)

The CC1101 is the chip on the E07 board, which requires many more connections besides just the microcontroller interface.  The E07 board has the following pins: 1 VDD, 2 GD00, 3 CSN, 4 SCK, 5 MOSI, 6 GD01, 7 GD02, 8 GND

If you're looking for more info on the CC1101 chip itself, you can find more info here:
[Texas Instruments CC1101](http://www.ti.com/product/CC1101)

**Comment by PreethamRU** [comment]
Hey, Thanks for the information.

However, I saw the pinout, it's little confusing. CC1101 connections where should they be connected on MSP430 ?

**Comment by PreethamRU** [comment]
]

**Comment by PreethamRU** [comment]
HI, thanks for this.  However, whenever I run this, once take out from USB and put it on power bank, the chip is unable to send. Is there anything I need to do in the code ?

**Comment by PreethamRU** [comment]
worked, thanks for the help :)
